### ISSUE TITLE
PandasRollingOLS reports ValueError 

### ISSUE THREAD

**Issue by zhangda425** [bsolomon1124/pyfinance#11]
the following code cannot work and report ValueError. hope to see a better version soon, thx.

from pyfinance import ols
data = {'A':[2,3,4,5,6],'B':[10,11,12,13,14]}
df = pd.DataFrame(data)
rolling = ols.RollingOLS(y=df['B'], x=df['A'], window=3,has_const=False,use_const=False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\utils.py", line 705, in rolling_windows
    ' `a`, {1}.'.format(window, a.shape[0]))

ValueError: Specified `window` length of 3 exceeds length of `a`, 1.

**Comment by zhangda425** [comment]
**I fix the bug above by adding**    
 if x.shape[0]==1:
      x=x.T
**into the function _clean_xy. But when I call the property rsq of rolling, there bumps another bug.**


from pyfinance import ols
data = {'A':range(0,500),'B':range(500,1000)}
df = pd.DataFrame(data)
y=df['B']
x=df['A']
rolling = ols.PandasRollingOLS(y=y, x=x, window=3,has_const=False,use_const=False)
rolling.rsq
Traceback (most recent call last):

  File "<ipython-input-37-ee2ef37a71f7>", line 1, in <module>
    rolling.rsq

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\ols.py", line 822, in rsq
    return self._wrap_series(stat='_rsq')

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\ols.py", line 749, in _wrap_series
    return Series(getattr(self, stat), index=self.ridx, name=name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\ols.py", line 471, in _rsq
    return self._ss_reg / self._ss_tot

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\ols.py", line 459, in _ss_reg
    return np.sum(np.square(self._predicted

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfinance\ols.py", line 426, in _predicted
    axis=-1)))

ValueError: shapes (498,3) and (498,1) not aligned: 3 (dim 1) != 498 (dim 0)

**Comment by zhangda425** [comment]
it seems that you use matrix multiplication.  should it be dot multiplication? I don't know. it takes so much efforts to fix them........

def _predicted(self):
        """The predicted values of y ('yhat')."""
        return np.squeeze(np.matmul(self.xwins, np.expand_dims(self.solution,
                                                               axis=-1)))

**Comment by bsolomon1124** [comment]
The original `ValueError: Specified window length of 3 exceeds length of a, 1.` no longer reproduces on **v2.0.1** — the exact repro from this issue constructs cleanly now.

Your follow-up comment identified a separate bug in `rsq` / `rsq_adj` when constructed with `use_const=False` (values outside [0, 1]). That's a different code path (the R² formula is wrong when no intercept is used) and it's still present — I've left it tracked under #13, which is the clearer reproducer of that specific issue.

Release: <https://pypi.org/project/pyfinance/2.0.1/>

Closing this one for the original error. Thanks for the detailed investigation!
