### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kite8** [bsolomon1124/pyfinance#14]
I use git to pull the code, then I use the command `python -m pip install -e .`
then there is a error
```
(quant) E:\Python\quantaxis\pyfinance>python -m pip install -e .
Looking in indexes: http://pypi.douban.com/simple/
Obtaining file:///E:/Python/XXX/pyfinance
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\Python\XXX\pyfinance\setup.py", line 8, in <module>
        with open(os.path.join(here, 'README.rst'), encoding='utf-8') as f:
      File "E:\ProgramData\Anaconda3\envs\quant\lib\codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Python\\XXX\\pyfinance\\README.rst'
```

So I change the 'README.rst' to 'README.md', then is OK.

**Comment by lefig** [comment]
Thanks for the fix as I had this problem too.

**Comment by bsolomon1124** [comment]
The old `setup.py` that hard-coded `README.rst` is gone as of **v2.0.1**; packaging is now fully declared in `pyproject.toml` (`readme = "README.md"`) using the `uv_build` backend. Editable installs work via `uv sync` / `pip install -e .` without the rename.

Release: <https://pypi.org/project/pyfinance/2.0.1/>

Thanks @lefig for confirming the workaround back then. Closing.
