### ISSUE TITLE
Installation via pip doesn't work

### ISSUE THREAD

**Issue by miqbal92** [bsolomon1124/pyfinance#7]
First - thanks for this package, it sounds amazing.

The issue I'm facing is actually in installation - keep getting the following error after (installing via pip in anaconda):
!pip3 install pyfinance
Collecting pyfinance
  Using cached https://files.pythonhosted.org/packages/74/20/7dd8767ec785cfcdce714e170a0a7b1c79feb7085e6217ec8dc43b4a74d3/pyfinance-1.1.1.tar.gz
Requirement already satisfied: beautifulsoup4>=4.6.0 in c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages (from pyfinance) (4.6.0)
Requirement already satisfied: matplotlib>=1.1 in c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages (from pyfinance) (2.1.0)
Requirement already satisfied: numpy>=0.7.0 in c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages (from pyfinance) (1.13.3)
Exception:
Traceback (most recent call last):
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages\pip\_internal\resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\site-packages\pip\_internal\utils\packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "c:\users\mi113\appdata\local\continuum\anaconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by bsolomon1124** [comment]
Hi @miqbal92 : just wanted to make sure this issue went away?

I'm not seeing any error when installing via pip on Mac OSX or Linux Ubuntu.
